### ISSUE TITLE
'AdyenCSE/AdyenCSE.h' file not found

### ISSUE THREAD

**Issue by zerazeru** [chocnut/RNAdyenCse#1]
```
react-native-adyen-cse/ios/RNAdyenCse.m:3:9: fatal error: 'AdyenCSE/AdyenCSE.h' file not found
#import "AdyenCSE/AdyenCSE.h"
        ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Got this error when building for ios.

I think the AdyenCSE header should be imported with angle brackets:
```c
#import <AdyenCSE.h>
```

**Comment by chocnut** [comment]
@zerazeru thanks. I'll do a test first 👍

**Comment by zerazeru** [comment]
Perfect, thanks! I made a PR too, that works for me, but am not sure that's the right way so any other solutions are welcome.

If an xcode project is added to another one as a Library, shouldn't it use the parent project's header search paths too? I am not sure what's the standard way to tell that to xcode or how to solve this in the parent project without touching the child.
