### ISSUE TITLE
Android build fails if root project sdk >23

### ISSUE THREAD

**Issue by zerazeru** [chocnut/RNAdyenCse#3]
`AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.`

I'm not opening a new PR but see this commit for a solution that worked for me: zerazeru/RNAdyenCse@be04b269b4174d1926c978d6cbdeaa8a16024e3e

**Comment by chocnut** [comment]
can you please send a PR I'll do a test.

**Comment by zerazeru** [comment]
#4, there you go, thanks

**Comment by chocnut** [comment]
cool checking it out

**Comment by chocnut** [comment]
It's merged
